### PR TITLE
Add check for logged in user for all VerseCheck functions

### PR DESCRIPTION
**Pull request by ihoegen**
To tes this PR, open a tool, and try doing some of the Verse Check functions while not logged in

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/42)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Container.js, line 49 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/42#-Kjb9FYTFVTXg5jhu9-A:-Kjb9FYUbzCwm_YoRnjD:b-svfjr4) ([raw file](https://github.com/translationcoreapps/versecheck/blob/5a274a3c8483097965b17cf6f7be4805b7dee627/Container.js#L49)):*
> ```JavaScript
>         if (!that.props.loginReducer.loggedInUser) {
>           that.props.actions.selectModalTab(1, 1, true);
>           that.props.actions.showNotification("You must be logged in to save progress", 5);
> ```

you may want to use openAlertDialog() instead of showNotification()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/42)*

**Comment by ihoegen** [comment]
@mannycolon Should I use it for all the notifications on verse check, or only on the Save function?

**Comment by klappy** [comment]
*[Container.js, line 49 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/42#-Kjb9FYTFVTXg5jhu9-A:-KjdaVNFQGMLVxomOzUw:btabf03) ([raw file](https://github.com/translationcoreapps/versecheck/blob/5a274a3c8483097965b17cf6f7be4805b7dee627/Container.js#L49)):*
> openAlertDialog()
That doesn't appear to be in the core passed down to the tools yet... but showNotification is exposed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/42)*

**Comment by klappy** [comment]
*[Container.js, line 49 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/42#-Kjb9FYTFVTXg5jhu9-A:-KjdajiRxeHAjSOZAy1B:b-gaw0c) ([raw file](https://github.com/translationcoreapps/versecheck/blob/5a274a3c8483097965b17cf6f7be4805b7dee627/Container.js#L49)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

> openAlertDialog()
That doesn't appear to be in the core passed down to the tools yet... but showNotification is exposed.
</blockquote></details>

Should we go ahead and merge this and once it's exposed, update it here?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/42)*

**Comment by ihoegen** [comment]
@klappy I looked, I'm pretty sure it is exposed.

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/42#-:-Kje9d9oH9NW44cvkN9O:bnfp4nl)*

**Pull request merged**
