### PR TITLE
React 16

### PR DESCRIPTION
**Pull request by RoyalSix**
#### This pull request addresses:
This PR adds React 16 compatibility

#### How to test this pull request:
run ```npm test```
Use component in main app and ensure usual functionality

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/87)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 10 of 10 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---

*[package.json, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zQkUZLwM93qygugum:-L2zQkU_-6rq0GhA4ews:bof1te3) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/package.json#L40)):*
> ```JSON
>     "eslint": "^4.13.1",
>     "eslint-plugin-react": "^7.5.1",
>     "fs-extra": "3.0.1",
> ```

add the latest version of fs-extra

---

*[package.json, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zQuqUv6OceK0qpKRc:-L2zQuqUv6OceK0qpKRd:bj6igly) ([raw file](https://github.com/translationcoreapps/versecheck/blob/2ded7087da39139f0aac8d26440dcd1fe3327329/package.json#L40)):*
> ```JSON
>     "lodash": "^4.17.4",
>     "material-ui": "^0.20.0",
>     "react": "^15.6.2",
> ```

we dont need react ???

---

*[package.json, line 44 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zQpqynJhHRarO6Nbk:-L2zQpqynJhHRarO6Nbl:b54pwii) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/package.json#L44)):*
> ```JSON
>     "jsdom": "^11.3.0",
>     "lodash": "^4.17.4",
>     "material-ui": "0.17.4",
> ```

why did you lower the material-ui version?

---

*[package.json, line 53 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zR1J_KaDXO4Tlk3TV:-L2zR1J_KaDXO4Tlk3TW:b-cyy30i) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/package.json#L53)):*
> ```JSON
>     "react-remarkable": "1.1.3",
>     "react-test-renderer": "^15.6.2",
>     "usfm-js": "1.0.0-beta.17.2",
> ```

do we use these libraries?

---

*[__tests__/MyLanguageModal.test.js, line 39 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zR63WcX18im57hPeU:-L2zR63WcX18im57hPeV:b-1mzats) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/__tests__/MyLanguageModal.test.js#L39)):*
> ```JavaScript
> 
> function validateModalTitle(enzymeWrapper, expectedTitle) {
>   let titleHeader = enzymeWrapper.find(Modal.Title);
> ```

why did you change this to a variable?

---

*[__tests__/View.test.js, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zRrpq37lIRmoPwvND:-L2zRrpq37lIRmoPwvNE:bdezu1x) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/__tests__/View.test.js#L40)):*
> ```JavaScript
>       saveSelection: () => jest.fn()
>     };
>     let component = (
> ```

why not a const?

---

*[testSetup/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zSVzo-ZzZSDcg9a5Y:-L2zSVzo-ZzZSDcg9a5Z:brmwqq9) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/testSetup/shim.js#L1)):*
> ```JavaScript
> global.requestAnimationFrame = (callback) => {
> ```

why do we need shim.js?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87)*

**Comment by PhotoNomad0** [comment]
Reviewed 7 of 12 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87)*

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87)*

**Comment by mannycolon** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-:-L3UN8yFbLK6RuhM71Mn:bnfp4nl)*

**Comment by RoyalSix** [comment]
Review status: 8 of 10 files reviewed at latest revision, 7 unresolved discussions.

---

*[package.json, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zQkUZLwM93qygugum:-L3UNEErG3DpXjY8fRGr:b-896fix) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/package.json#L40)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

add the latest version of fs-extra
</blockquote></details>

Done.

---

*[package.json, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zQuqUv6OceK0qpKRc:-L3UNJnIMY8NjgxhKmiB:b-y083xm) ([raw file](https://github.com/translationcoreapps/versecheck/blob/2ded7087da39139f0aac8d26440dcd1fe3327329/package.json#L40)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

we dont need react ???
</blockquote></details>

We do.

---

*[package.json, line 44 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zQpqynJhHRarO6Nbk:-L3UNI6dRlIfgx4JOobB:b-t158lp) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/package.json#L44)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did you lower the material-ui version?
</blockquote></details>

Fixed to latest.

---

*[package.json, line 53 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zR1J_KaDXO4Tlk3TV:-L3UNKdEo1Y1CP8B1MLP:b2nhky0) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/package.json#L53)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

do we use these libraries?
</blockquote></details>

No.

---

*[__tests__/MyLanguageModal.test.js, line 39 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zR63WcX18im57hPeU:-L3UNmzifcFYzsa7ZjVk:b-omsasu) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/__tests__/MyLanguageModal.test.js#L39)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why did you change this to a variable?
</blockquote></details>

Im assuming by variable you mean "using let". Fixed.

---

*[__tests__/View.test.js, line 40 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zRrpq37lIRmoPwvND:-L3UNvR43oMZNEsR9AfO:bt2vr1b) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/__tests__/View.test.js#L40)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why not a const?
</blockquote></details>

Fixed.

---

*[testSetUp/shim.js, line 1 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-L2zSVzo-ZzZSDcg9a5Y:-L3UNwVAq03h0CeCrkcp:bm2m0sn) ([raw file](https://github.com/translationcoreapps/versecheck/blob/0d476e40c92abd059145657e43d7e221a3300785/testSetUp/shim.js#L1)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

why do we need shim.js?
</blockquote></details>

For react to work with material-ui

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87)*

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/87#-:-L3Y4zcHdEwpmkEa3xpn:bnfp4nl)*

**Pull request merged**
