### PR TITLE
Feature - #1279 - Adds titles to expanded target language pane

### PR DESCRIPTION
**Pull request by richmahn**
#### This pull request addresses:

Addresses Issue https://github.com/unfoldingWord-dev/translationCore/issues/1279 for the expanded my language's title

#### How to test this pull request:

Go to tW tool for a project and in "Step 2" expand the scripture of the selected verse to view the chapter. The title of the modal should be the name of the Bible book.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/82)

### CODE REVIEW

**Comment by RoyalSix** [comment]
@richmahn The tests are failing.

**Comment by richmahn** [comment]
@RoyalSix Ok, was a unit test I didn't write but didn't include its package in packages.json. Updated.

**Comment by RoyalSix** [comment]
Reviewed 4 of 4 files at r1, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/DefaultArea.js, line 81 at r3](https://reviewable.io:443/reviews/translationcoreapps/versecheck/82#-Kz0zvOaaGElIVfBHMbA:-Kz0zvObXCsK2hVaaPos:b5pg890) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b115cee3f34143649324049cfee168877ed3cc3b/src/components/DefaultArea.js#L81)):*
> ```JavaScript
>             {this.state.modalVisibility ?
>               <MyLanguageModal {...this.props}
>                 show={this.state.modalVisibility}
> ```

Its usually best practice to only pass down the props you need, that way the component doesn't re-render for props that its not even using.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/82)*

**Comment by richmahn** [comment]
Review status: 3 of 5 files reviewed at latest revision, 1 unresolved discussion.

---

*[src/components/DefaultArea.js, line 81 at r3](https://reviewable.io:443/reviews/translationcoreapps/versecheck/82#-Kz0zvOaaGElIVfBHMbA:-Kz147JmCoOyvsG6-6pB:b-896fix) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b115cee3f34143649324049cfee168877ed3cc3b/src/components/DefaultArea.js#L81)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Its usually best practice to only pass down the props you need, that way the component doesn't re-render for props that its not even using.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/82)*

**Comment by RoyalSix** [comment]
Reviewed 2 of 2 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/82)*

**Pull request merged**
