### PR TITLE
Bugfix/klappy/blankverses/#1965#1968

### PR DESCRIPTION
**Pull request by klappy**
## This PR addresses:

- Bad grammar in the confirmation dialog of saving blank verse.
- Changing state in render error in console after confirming the deletion of a blank verse.

## To Test:

- Delete the text of a verse in edit mode.
- Review the grammar of the text, it should say "You are saving a blank verse. Please confirm."
- Open the dev console and make sure no errors show when clicking "Save blank verse" button.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/56)

### CODE REVIEW

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/56#-:-KnjE_rN1wFhZZNLQwgk:bnfp4nl)*

**Comment by mannycolon** [comment]
I still need to test the branch

**Comment by RoyalSix** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/56#-:-KnkMvEF11JZSL3lXP0L:bnfp4nl)*

**Comment by mannycolon** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/56#-:-KnmgX-GeRb7YuU2pOio:bnfp4nl)*

**Pull request merged**
