### PR TITLE
Bugfix #4145/Fix localization gaps

### PR DESCRIPTION
**Pull request by PhotoNomad0**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Finish Localization for VerseCheck tool

#### Please include detailed Test instructions for your pull request:
- This PR to be tested with latest develop branch and depends on https://github.com/translationCoreApps/translationWords/pull/118
- Should see following fixes:
  - [ ] localize Step 1, select, "Please  select..."
  - [ ] localize Step 1 buttons: "Cancel", etc.
  - [ ] localize Step 2 buttons: "Bookmark", "Save and Previous", "Select", etc.
  - [ ] localize Step 2: "has been translated","no selection has been made"
  - [ ] localize Comment Box prompt and buttons
  - [ ] localize Edit Verse prompt and buttons

(merge https://github.com/translationCoreApps/translationWords/pull/118 before merging this)

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/97)

### CODE REVIEW

**Comment by richmahn** [comment]
Also a :LGTM: once test coverage increased.

---

Reviewed 20 of 21 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/97#-:-L8nzbUL8YrrZOxqrZlO:b-nemf0s)*

**Comment by PhotoNomad0** [comment]
Improved code coverage

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/97)*

**Comment by mannycolon** [comment]
Found the following missing localized string

screen shot 2018-03-30 at 8 58 47 am

**Comment by mannycolon** [comment]
Also here in the expanded target language bible

screen shot 2018-03-30 at 9 00 42 am

**Comment by mannycolon** [comment]
When I click next without making a selection

screen shot 2018-03-30 at 9 04 04 am

**Comment by mannycolon** [comment]
Also here

screen shot 2018-03-30 at 9 06 32 am

**Comment by PhotoNomad0** [comment]
@mannycolon @richmahn  - added more localization

**Comment by richmahn** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r3, 13 of 13 files at r4.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/97#-:-L8sLkV358FyrT9Dfxo1:bnfp4nl)*

**Pull request merged**
