### PR TITLE
UI Updates To Check Area

### PR DESCRIPTION
**Pull request by RoyalSix**
Refer to https://github.com/unfoldingWord-dev/translationCore/issues/2290 for specifications of requirements.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/67)

### CODE REVIEW

**Comment by klappy** [comment]
*[Container.js, line 248 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzT0jeFSUcI3xUn_K:-KsnzT0jeFSUcI3xUn_L:bg083ps) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/Container.js#L248)):*
> ```JavaScript
>     let verseText = "";
>     if (targetLanguage && targetLanguage[chapter] && bookId == bookAbbr) {
>       verseText = targetLanguage[chapter][verse] || "";
> ```

This should help hide the "undefined" printed on the screen.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
*[components/DirectionsArea.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzkPolq3J4AzlO4D0:-KsnzkPolq3J4AzlO4D1:b6rqhwp) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/DirectionsArea.js#L12)):*
> ```JavaScript
> }) => {
> 
>   if (!verseText) {
> ```

Will this handle when `verseText` is ""? I think the code returns "" if the verse is undefined.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
*[components/DirectionsArea.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzkPolq3J4AzlO4D0:-Kso-8XX1eOBupiKofZL:ba6pimm) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/DirectionsArea.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Will this handle when `verseText` is ""? I think the code returns "" if the verse is undefined.
</blockquote></details>

Okay, looks like it does. I just tested it in the console.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
I'm having difficulty and wondering if you see what I do.

When a verse doesn't have a selection yet, it goes into the select mode like it should but shows the text saying "..." has been translated as: (blank).



---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-:-Kso2Kc6aLLUK0fhEByN:b-kpwnb0)*

**Comment by mannycolon** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[components/DirectionsArea.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzkPolq3J4AzlO4D0:-Kssod-MjYljYqX2LcwS:b5ttlgz) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/DirectionsArea.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Okay, looks like it does. I just tested it in the console.
</blockquote></details>

I was wondering if we want to change the name of this component from `DirectionsArea` to `InstructionsArea`. what do you guys think?

---

*[components/SelectionArea.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KssosshY7oS7Ae-vu_P:-KssosshY7oS7Ae-vu_Q:b9ao81d) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/SelectionArea.js#L5)):*
> ```JavaScript
> import { selectionArray, occurrencesInString, normalizeString } from '../utils/selectionHelpers';
> import style from '../css/Style';
> import MyLanguageModal from './MyLanguageModal'
> ```

I thought we didn't want the modal in the selection area?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
The above issue that I shared the screenshot is still happening.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-:-KstmncaR8KV-ympmZlz:b-9zf5ae)*

**Comment by RoyalSix** [comment]
@klappy What is the expected behavior?

**Comment by RoyalSix** [comment]
Review status: 0 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/DirectionsArea.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzkPolq3J4AzlO4D0:-Kst5_pJ61tZKC2XJEK0:barruh) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/DirectionsArea.js#L12)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I was wondering if we want to change the name of this component from `DirectionsArea` to `InstructionsArea`. what do you guys think?
</blockquote></details>

I don't really see a difference in those words, any reason we should change them?

---

*[components/SelectionArea.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KssosshY7oS7Ae-vu_P:-Kstxq_Yn4YfCnWayTDw:byr4flj) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/SelectionArea.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

I thought we didn't want the modal in the selection area?
</blockquote></details>

Right.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
*[components/DirectionsArea.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzkPolq3J4AzlO4D0:-Ksu07Mk83VGfVXtYjkR:bx2kyio) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/DirectionsArea.js#L12)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

I don't really see a difference in those words, any reason we should change them?
</blockquote></details>

Consistency most likely. Using the same noun as in the core for home screen. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
According to the story: 

- [x] *When in Select mode...*
  - [x] The translation should stay on the left-hand side
    - [x] It should appear the same way as the Main Mode: 
      - [x] Language name on the top
      - [x] Bible reference underneath
      - [x] passage under that
      - [x] passage color should now be black
  - [x] The verbiage on the righthand side should say:
`Please select the translation for: [ABC]`
  - [x] If the verse is missing, the righthand side should say: 
`No selection can be made because the verse is blank. `
`You may fix this by editing the verse.`
`If desired, you may also leave a comment or bookmark this check.`

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-:-Ksu4umtU_M3y6pzMCdX:b-6deygl)*

**Comment by klappy** [comment]
*[components/SelectionArea.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KssosshY7oS7Ae-vu_P:-Ksu5sTbaW-oFs1bO3Ad:b-4xcplf) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/SelectionArea.js#L5)):*
<details><summary><i>Previously, RoyalSix (Sterling (Jay) Scott) wrote…</i></summary><blockquote>

Right.
</blockquote></details>

I would check with ben and koz. That's something that it could fail over since the story does say "It should appear the same way as in Main mode"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by mannycolon** [comment]
Reviewed 2 of 8 files at r2, 5 of 6 files at r3, 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by mannycolon** [comment]
@RoyalSix Merge with master branch

**Comment by RoyalSix** [comment]
Review status: 4 of 8 files reviewed at latest revision, 3 unresolved discussions.

---

*[components/DirectionsArea.js, line 12 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzkPolq3J4AzlO4D0:-KtI_ZRhcUvoNlIBIFhW:b-896fix) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/DirectionsArea.js#L12)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

Consistency most likely. Using the same noun as in the core for home screen. 
</blockquote></details>

Done.

---

*[components/SelectionArea.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KssosshY7oS7Ae-vu_P:-KtI_aiRTJgnfM4aDiH4:b-896fix) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/components/SelectionArea.js#L5)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I would check with ben and koz. That's something that it could fail over since the story does say "It should appear the same way as in Main mode"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
Reviewed 2 of 9 files at r2, 5 of 7 files at r3, 1 of 1 files at r4, 6 of 6 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
*[Container.js, line 248 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-KsnzT0jeFSUcI3xUn_K:-KtJkjNkPLOnnd4V--BA:b32w0x) ([raw file](https://github.com/translationcoreapps/versecheck/blob/b831b68451bece7d6f795d81e2b25a8d0bf10c09/Container.js#L248)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

This should help hide the "undefined" printed on the screen.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67)*

**Comment by klappy** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/67#-:-KtJlFrSpaWzYMSwIzF0:bnfp4nl)*

**Pull request merged**
