### PR TITLE
Fixed Selection Bug

### PR DESCRIPTION
**Pull request by mannycolon**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/86)

### CODE REVIEW

**Comment by klappy** [comment]
*[src/helpers/windowSelectionHelpers.js, line 104 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/86#-L2gR3r7kAZYNaELncAh:-L2gR3r7kAZYNaELncAi:bmk9hxp) ([raw file](https://github.com/translationcoreapps/versecheck/blob/2ded7087da39139f0aac8d26440dcd1fe3327329/src/helpers/windowSelectionHelpers.js#L104)):*
> ```JavaScript
>   let previousSibling = element.previousElementSibling;
>   // loop through previous spans to get their text
>   while (previousSibling) {
> ```

If I remember correctly, the while loops through to look for preceding text when there is more than one preceding element. This loop is important when there are multiple selections prior to the current one.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/86)*

**Comment by klappy** [comment]
*[src/helpers/windowSelectionHelpers.js, line 104 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/86#-L2gR3r7kAZYNaELncAh:-L2gUf8xP8oXFVWHTMB7:b32w0x) ([raw file](https://github.com/translationcoreapps/versecheck/blob/2ded7087da39139f0aac8d26440dcd1fe3327329/src/helpers/windowSelectionHelpers.js#L104)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

If I remember correctly, the while loops through to look for preceding text when there is more than one preceding element. This loop is important when there are multiple selections prior to the current one.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/86)*

**Comment by klappy** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/86)*

**Comment by klappy** [comment]
*[src/helpers/windowSelectionHelpers.js, line 104 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/86#-L2gWlsVxXXjfVmyydfW:-L2gWlsVxXXjfVmyydfX:b-ld2cjw) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f2ba5a08dee3a34a0f43c9ba071d666f1542f2eb/src/helpers/windowSelectionHelpers.js#L104)):*
> ```JavaScript
>     let previousSibling;
>     // get the previous sibling to start the loop
>     if (element.previousElementSibling) {
> ```

I think that this block needs to happen again inside of the loop. It's missing the conditions when in the loop and if you have multiple repeats and selections it can throw it off if not just one.
1) verse =  `abcabc abcabc abcabc`
2) select the second and third `abc`: 

3) select the second `ca` that overlaps the second selection and it highlights the third that is standalone and not overlapping instead of extending the second selection by one character:


The result should look like this:


---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/86)*

**Comment by RoyalSix** [comment]
Is this PR ready? What else needs to be done? @mannycolon @klappy

**Comment by klappy** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/86)*

**Pull request closed without merging**
