### PR TITLE
VerseCheck Initial

### PR DESCRIPTION
**Pull request by klappy**
### This PR Addresses:
Initial implementation of new design for Selection, Edit verse, Commenting, etc….

### To Test this PR:
Check out PR #46 on translationWords: https://github.com/translationCoreApps/translationWords_Check_plugin/pull/46

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/1)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 15 of 15 files at r1.
Review status: all files reviewed at latest revision, 15 unresolved discussions.

---

*[Container.js, line 18 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8bF_5s6LJv5pdFBwB:-Kf8bF_5s6LJv5pdFBwC:blatlar) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L18)):*
> ```JavaScript
>     this.lastCheck = props.currentCheck
> 
>     let that = this
> ```

usually people use `_this` instead of `that`

---

*[Container.js, line 54 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8btLBJ-qSdfecLUIR:-Kf8btLBJ-qSdfecLUIS:b5wnuas) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L54)):*
> ```JavaScript
>         let newState = that.state
>         const checked = e.target.value == 'on'
>         console.log(tag, checked)
> ```

remove console log

---

*[Container.js, line 87 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cOhnacavHJtJhR2V:-Kf8cOhnacavHJtJhR2W:b-vnvrm6) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L87)):*
> ```JavaScript
> 
>   componentWillMount() {
>     //get default resources (originalLang, targetLang, gatewayLang) content
> ```

this comment seems to be off

---

*[Container.js, line 92 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cQXA0_B3y-U-ASuK:-Kf8cQXA0_B3y-U-ASuL:b-5s9yku) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L92)):*
> ```JavaScript
> 
>   componentWillReceiveProps(nextProps) {
>     this.resetState();
> ```

im not sure if im a fan of the resetState() function lol

---

*[Container.js, line 95 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cC1k5HBBK90t9Txh:-Kf8cC1k5HBBK90t9Txi:bx575yh) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L95)):*
> ```JavaScript
>   }
> 
>   // shouldComponentUpdate(nextProps, nextState) {
> ```

this can be removed we dont need it anymore

---

*[components/actionsArea.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8ceWhjE8d8n3ShAGs:-Kf8ceWhjE8d8n3ShAGt:b-yp3fk9) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/actionsArea.js#L2)):*
> ```JavaScript
> const React = require('react')
> const RB = api.ReactBootstrap
> ```

how about we stop using the api

import {Col, Button, Glyphicon} from 'react-bootstrap'
 is a better way to do this now.

same for react
we want to start using ES6 conventions

import react from 'react'

---

*[components/actionsArea.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cytXlv6Ogfq7hZQK:-Kf8cytXlv6Ogfq7hZQL:bfnndhb) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/actionsArea.js#L5)):*
> ```JavaScript
> const {Col, Button, Glyphicon} = RB
> 
> var ActionsArea = function(props) {
> ```

 let ActionsArea = (props) =>  {

ES6 CONVENTION

---

*[components/checkArea.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8dk62KakHUkYvaYoI:-Kf8dk62KakHUkYvaYoJ:bnj7hl0) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/checkArea.js#L2)):*
> ```JavaScript
> const React = require('react')
> const RB = api.ReactBootstrap
> ```

same as above

---

*[components/checkArea.js, line 6 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8dleA87jveGriq4nb:-Kf8dleA87jveGriq4nc:b5bb6j2) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/checkArea.js#L6)):*
> ```JavaScript
> 
> const SelectArea = require('./selectArea')
> const DirectionsArea = require('./directionsArea')
> ```

same as above 
import CommentArea from './CommentArea'

---

*[components/checkArea.js, line 10 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8dvDoffurLVlQALEP:-Kf8dvDoffurLVlQALEQ:ber0ub1) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/checkArea.js#L10)):*
> ```JavaScript
> const CommentArea = require('./commentArea')
> 
> var CheckArea = function(props) {
> ```

 let CheckArea = (props) =>  {

---

*[components/commentArea.js, line 6 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8e1IWhIj_MxxcS3bg:-Kf8e1IWhIj_MxxcS3bh:b-l9afuk) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/commentArea.js#L6)):*
> ```JavaScript
> const {FormGroup, FormControl, Glyphicon} = RB
> 
> var CommentArea = function(props) {
> ```

 let CommentArea = (props) =>  {

---

*[components/directionsArea.js, line 3 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8e49phUoulOjIeBWu:-Kf8e49phUoulOjIeBWv:b71x1a1) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/directionsArea.js#L3)):*
> ```JavaScript
> const React = require('react')
> 
> var DirectionsArea = function(props) {
> ```

 let DirectionsArea = (props) =>  {

---

*[components/editVerseArea.js, line 6 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8e8j_4uA9D5OlbzSx:-Kf8e8j_4uA9D5OlbzSy:b5d9fsg) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/editVerseArea.js#L6)):*
> ```JavaScript
> const {FormGroup, FormControl, Glyphicon, Checkbox} = RB
> 
> var EditVerseArea = function(props) {
> ```

 let EditVerseArea = (props) =>  {

---

*[components/saveArea.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8eCWIPgAe8EVopM3F:-Kf8eCWIPgAe8EVopM3G:bao17fm) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/saveArea.js#L5)):*
> ```JavaScript
> const {Row, Col, Button, Glyphicon} = RB
> 
> var SaveArea = function(props) {
> ```

 let SaveArea = (props) =>  {

---

*[components/view.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8eM1GqzTiOTHqmhz5:-Kf8eM1GqzTiOTHqmhz6:bfns7xv) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/view.js#L5)):*
> ```JavaScript
> const React = api.React
> const RB = api.ReactBootstrap
> const {Row, Glyphicon, Col, Button} = RB
> ```

same please dont use api

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[Container.js, line 18 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8bF_5s6LJv5pdFBwB:-Kf8gIOJUS5LJWdggDOT:b-e60lbu) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L18)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

usually people use `_this` instead of `that`
</blockquote></details>

I always used _this until Jdubz convinced me to use that for some reason, and I've just gotten into the habit :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[Container.js, line 92 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cQXA0_B3y-U-ASuK:-Kf8gb6DjJJiUxa8iQiG:b-rzz402) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L92)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

im not sure if im a fan of the resetState() function lol
</blockquote></details>

I hate it! It's temporary until we refactor it and move state up the tree.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[Container.js, line 87 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cOhnacavHJtJhR2V:-Kf8gkwbN4Abok0Zotx-:bhsagfe) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L87)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this comment seems to be off
</blockquote></details>

Another copied and pasted section, I'll clean it up.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[components/actionsArea.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cytXlv6Ogfq7hZQK:-Kf8iVaRyJs_XeHiM3c9:b4855pb) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/actionsArea.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

 let ActionsArea = (props) =>  {

ES6 CONVENTION

</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[components/actionsArea.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8ceWhjE8d8n3ShAGs:-Kf8iZOkzmTGzQpaLt0U:b4855pb) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/actionsArea.js#L2)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

how about we stop using the api

import {Col, Button, Glyphicon} from 'react-bootstrap'
 is a better way to do this now.

same for react
we want to start using ES6 conventions

import react from 'react'
</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[Container.js, line 95 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8cC1k5HBBK90t9Txh:-Kf8i_eafHuZOt0F8MVq:b4855pb) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L95)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

this can be removed we dont need it anymore
</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[Container.js, line 54 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8btLBJ-qSdfecLUIR:-Kf8ibaKH5z_InVNyMXy:b4855pb) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L54)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

remove console log
</blockquote></details>

Thanks! Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[components/checkArea.js, line 2 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8dk62KakHUkYvaYoI:-Kf8kAb1DXfl5E-7o27R:b-ezeo3c) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/checkArea.js#L2)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same as above
</blockquote></details>

I'm applying these to all files...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[components/checkArea.js, line 6 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8dleA87jveGriq4nb:-Kf8kDfupU5xi-3WQMQm:b-ezeo3c) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/checkArea.js#L6)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same as above 
import CommentArea from './CommentArea'
</blockquote></details>

I'm applying these to all files...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[components/checkArea.js, line 10 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8dvDoffurLVlQALEP:-Kf8kF4-TeiZaxKwwXUe:b-ezeo3c) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/checkArea.js#L10)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

 let CheckArea = (props) =>  {
</blockquote></details>

I'm applying these to all files...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by klappy** [comment]
*[components/view.js, line 5 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8eM1GqzTiOTHqmhz5:-Kf8kK-X5eG4qCnlmh2O:b-ezeo3c) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/components/view.js#L5)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

same please dont use api
</blockquote></details>

I'm applying these to all files...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by ihoegen** [comment]
Reviewed 6 of 15 files at r1, 9 of 9 files at r2.
Review status: all files reviewed at latest revision, 17 unresolved discussions.

---

*[Container.js, line 18 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-Kf8bF_5s6LJv5pdFBwB:-KfA7XufErYpGyhWkSIM:bxvy5jj) ([raw file](https://github.com/translationcoreapps/versecheck/blob/f71e488c2aa82d2a9b81a273efa022bbb28a845b/Container.js#L18)):*
<details><summary><i>Previously, klappy (Christopher Klapp) wrote…</i></summary><blockquote>

I always used _this until Jdubz convinced me to use that for some reason, and I've just gotten into the habit :)
</blockquote></details>

I like the sound of using `that` instead actually, but usage can be avoided by using arrow functions. Arrow functions will continue to let you use `this`

---

*[FetchData.js, line 4 at r2](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-KfA7z9xnY7K4kcSjkMM:-KfA7z9xnY7K4kcSjkMN:b1br5h6) ([raw file](https://github.com/translationcoreapps/versecheck/blob/2575d5390ebc0070b8827a2346d688468c58a957/FetchData.js#L4)):*
> ```JavaScript
> 
> const api = window.ModuleApi;
> ```

I think some of our next steps should be removing a requirement for a FetchData, it'll help streamline tools. 

---

*[utils/selectionHelpers.js, line 189 at r2](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-KfA8VrxLAqHDmFi8dTJ:-KfA8VrxLAqHDmFi8dTK:brdelup) ([raw file](https://github.com/translationcoreapps/versecheck/blob/2575d5390ebc0070b8827a2346d688468c58a957/utils/selectionHelpers.js#L189)):*
> ```JavaScript
> //
> // Use the following lines to test the previous function
> // var string = "0123456789qwertyuiopasdfghjklzxcvbnmtyui01234567890"
> ```

Maybe move all these tests to their own files, this will let us integrate tests with the repo. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Comment by mannycolon** [comment]
Review status: all files reviewed at latest revision, 9 unresolved discussions.

---

*[FetchData.js, line 4 at r2](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1#-KfA7z9xnY7K4kcSjkMM:-KfRg33Ld0G-Hfy1EmGs:bup73ps) ([raw file](https://github.com/translationcoreapps/versecheck/blob/2575d5390ebc0070b8827a2346d688468c58a957/FetchData.js#L4)):*
<details><summary><i>Previously, ihoegen (Ian Hoegen) wrote…</i></summary><blockquote>

I think some of our next steps should be removing a requirement for a FetchData, it'll help streamline tools. 
</blockquote></details>

i agree

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/1)*

**Pull request merged**
