### PR TITLE
Inconsistent Handling of Disconnected Selections Fix

### PR DESCRIPTION
**Pull request by RoyalSix**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- This PR makes the quotations display the same as the what is shown on the gateway language.

#### Please include detailed Test instructions for your pull request:
- Open any project, open tW
- Make a selection of one word, ensure it has quotations around it.
- Make a selection of two words, ensure it has quotations around it.
- Make a selection of more than two words, ensure it has quotations around it, and an ellipsis inside it, substituted for the middle words.

Note: The changes will be displayed after saving a selection, and will be under `has been translated as:`

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/100)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Do not merge this yet

**Comment by mannycolon** [comment]
Reviewed 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[src/components/InstructionsAreaTextSelection.js, line 37 at r2](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/100#-L9B50hgCJXWetEaRy1h:-L9B50hgCJXWetEaRy1i:b5kriqx) ([raw file](https://github.com/translationcoreapps/versecheck/blob/ae82d176f092a2e9f82d7bf395178f2f624d1740/src/components/InstructionsAreaTextSelection.js#L37)):*
> ```JavaScript
> };
> 
> export const QuoatationMarks = ({ children }) => <strong style={{ color: 'var(--accent-color)' }}>{'"'}{children}{'"'}</strong>;
> ```

I don't think you need to export the QuoatationMarks and Ellipsis components

Great Job btw

---

*[src/helpers/windowSelectionHelpers.js, line 123 at r2](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/100#-L9B5J_R3uHEb_asqqVg:-L9B5J_S3TGsCTW-zkKa:b-8fx2u7) ([raw file](https://github.com/translationcoreapps/versecheck/blob/ae82d176f092a2e9f82d7bf395178f2f624d1740/src/helpers/windowSelectionHelpers.js#L123)):*
> ```JavaScript
>  * @returns {boolean} - Whether or not the View should display an ellipsis
>  */
> export function shouldRenderEllipsis(selections, verseText) {
> ```

:+1: 

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/100)*

**Comment by mannycolon** [comment]
Code Review: `LGTM`
Local test: `Pending`

**Comment by mannycolon** [comment]
Reviewed 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/translationcoreapps/versecheck/100)*

**Comment by mannycolon** [comment]
@RoyalSix 
Tested well just one issue

```
 Warning: Failed prop type: Invalid prop `children` of type `array` supplied to `QuoatationMarks`, expected `object`.
```

**Pull request merged**
