### PR TITLE
New select mode implementation 

### PR DESCRIPTION
**Pull request by mannycolon**
# Tests
- Now you should not be able to make selections in the default text area
- To make a selection now you must click select.
- Instructions are above the selectable text.
- CommentMode & VerseEdit mode still work.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/58)

### CODE REVIEW

**Comment by klappy** [comment]
Reviewed 9 of 9 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/58)*

**Comment by klappy** [comment]
Looks good and performs well.

Here is one thing that I think was overlooked from the original description for the Story:
- [ ] If a selection has been made, it should read:
"[English selection]
has been translated as:
[target language selection]"

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/58#-:-Kot9isGFqnV598H-bM2:br4php4)*

**Comment by mannycolon** [comment]
@klappy I just pushed the changes to address rendering the proper selection message

**Comment by klappy** [comment]
Reviewed 1 of 9 files at r1, 4 of 4 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/58)*

**Pull request merged**
