### PR TITLE
Enhancement - #4032 - Verse Check Instruction shows aligned GL text instead of tW title

### PR DESCRIPTION
**Pull request by richmahn**
#### Describe what your pull request addresses (Please include relevant issue numbers):
- Makes the text in the Verse Check instructions box contain the aligned text from the GL rather than the tW article title

#### Please include detailed Test instructions for your pull request:
- Just get this branch checked out in the VerseCheck repo, run tC app, go to tW for a project, see that the text in the Verse Check instructions pane is clear about what to select based on the aligned GL (should be similar to the highlights). Try for English and Hindi. Should also show the GL text after selecting (two different instruction messages)
- See the Story for more details on what to expect (screen shots) and not to expect per conversation with Ben (https://github.com/unfoldingWord-dev/translationCore/issues/4032)
- Words that have punctuation such as "God's" and "self-controlled" (under the "discipline" group) should show with the punctuation, rather than ellipsis.

#### Standard Test Instructions for PR Review Process:

- [ ] Double check unit tests that have been written
- [ ] Check for documentation for code changes
- [ ] Check that there are not inadvertent commits to tC Apps when reviewing a tC Core PR
- [ ] Checkout the branch locally and ensure that app runs as expected
  - [ ] Ensure tests pass
  - [ ] Open and watch the console for errors
  - [ ] Make sure all actions perform as expected
  - [ ] Import and Load a new Project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Switch project to an existing project
  - [ ] Load a tool and perform basic actions
  - [ ] Switch tools and perform basic actions
  - [ ] Next time reverse the order of importing after loading an existing project
- [ ] Reviewer should double check the DoD in the ISSUE, including the “spirit” of the story
- [ ] Ask Ben or Koz if you have any concerns about implementation (especially UI related)

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/96)

### CODE REVIEW

**Comment by bspidel** [comment]
seems to function correctly.

**Comment by richmahn** [comment]
@bspidel Need more than that for a pass, haha. I know the code has a bunch of files, but most of it is just for testing VerseCheck, correcting some of the integration tests (from View.test.js to have all current verseObjects in its test data), and then testing the CheckArea and InstructionsArea that my code affects. The main to files where the logic is are CheckArea.js and the helper file it uses, checkAreaHelpers.js.

**Comment by PhotoNomad0** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r2, 20 of 21 files at r4, 1 of 1 files at r5.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/96#-:-L7yUAtFC6MmQ-Mifruv:bnfp4nl)*

**Comment by bspidel** [comment]
:lgtm:

---

Reviewed 2 of 6 files at r2, 20 of 21 files at r4, 1 of 1 files at r5.
Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/96#-:-L7zLKr6YfIpmVu_nfxc:bnfp4nl)*

**Pull request merged**
