### PR TITLE
bugfix: overlapping with multiple occurrences

### PR DESCRIPTION
**Pull request by klappy**
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/88)

### CODE REVIEW

**Comment by RoyalSix** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/88)*

**Comment by RoyalSix** [comment]
Code looks good. Checking out branch in a few.

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/88)*

**Comment by mannycolon** [comment]
Looks good to me

**Pull request merged**
