### PR TITLE
Implement file editing

### PR DESCRIPTION
**Pull request by ihoegen**
This pull request addresses the file editing feature. 

To test this pull request, test it with the branch `feature/ih-1043-verse-edit`, try with multiple verses.

---
This change is [Reviewable](https://reviewable.io/reviews/translationcoreapps/versecheck/15)

### CODE REVIEW

**Comment by mannycolon** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[Container.js, line 95 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/15#-KhSdK4qum2SMvAfXqjN:-KhSdK4qum2SMvAfXqjO:b-jlekdm) ([raw file](https://github.com/translationcoreapps/versecheck/blob/a22c0fb268bb97d85d7aa25dd2bb1b32f1718d91/Container.js#L95)):*
> ```JavaScript
>         let before = targetVerse
>         let username = loginReducer.userdata.username
>         actions.addVerseEdit(before, that.state.verseText, that.state.tags, username, contextIdReducer.contextId, projectDetailsReducer.projectSaveLocation);
> ```

as i mentioned in your other PR you dont need to add the contextID or the savelocation here you can get it directly from the action using the getState() function

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/15)*

**Comment by ihoegen** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[Container.js, line 95 at r1](https://reviewable.io:443/reviews/translationcoreapps/versecheck/15#-KhSdK4qum2SMvAfXqjN:-KhYsT5rV6y4UiG4EOvC:b-896fix) ([raw file](https://github.com/translationcoreapps/versecheck/blob/a22c0fb268bb97d85d7aa25dd2bb1b32f1718d91/Container.js#L95)):*
<details><summary><i>Previously, mannycolon (Manny Colon) wrote…</i></summary><blockquote>

as i mentioned in your other PR you dont need to add the contextID or the savelocation here you can get it directly from the action using the getState() function
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/translationcoreapps/versecheck/15)*

**Comment by mannycolon** [comment]
@ihoegen this PR seems unnecessary

**Comment by ihoegen** [comment]
Not true, I remove the line where verse text is set to undefined.

**Pull request merged**
